# Generated by Django 5.2.3 on 2025-06-15 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_alpha_part_char1', models.CharField(default='A', help_text="First character of the alphanumeric part (e.g., 'A' for SR-AA-0001)", max_length=1)),
                ('current_alpha_part_char2', models.CharField(default='A', help_text="Second character of the alphanumeric part (e.g., 'A' for SR-AA-0001)", max_length=1)),
                ('current_numeric_part', models.IntegerField(default=0, help_text='Current numeric value (0-9999)')),
            ],
            options={
                'verbose_name': 'Service Request ID Sequence',
                'verbose_name_plural': 'Service Request ID Sequences',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, help_text='Custom generated Service Request ID (e.g., SR-AA-0001)', max_length=15, unique=True)),
                ('title', models.CharField(help_text='Summary of the service request', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the service needed')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('pending_approval', 'Pending Approval'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('category', models.CharField(choices=[('software', 'Software Request'), ('hardware', 'Hardware Request'), ('account', 'Account Management'), ('network', 'Network Access'), ('printer', 'Printer Issue'), ('system', 'Desktop/Laptop Issue'), ('information', 'Information Request'), ('other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how the request was fulfilled', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='IT staff assigned to fulfill this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
