# Generated by Django 5.2.1 on 2025-06-03 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the asset (e.g., Dell XPS 15)', max_length=255)),
                ('asset_tag', models.CharField(help_text='Unique identifier for the asset (e.g., ASSET-001)', max_length=100, unique=True)),
                ('serial_number', models.CharField(blank=True, help_text="Manufacturer's serial number", max_length=255, null=True)),
                ('category', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('network', 'Network Device'), ('server', 'Server'), ('peripheral', 'Peripheral'), ('other', 'Other')], default='hardware', max_length=50)),
                ('status', models.CharField(choices=[('in_use', 'In Use'), ('in_stock', 'In Stock'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired'), ('disposed', 'Disposed')], default='in_use', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Physical location of the asset', max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description or specifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User currently assigned to this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IT Asset',
                'verbose_name_plural': 'IT Assets',
                'ordering': ['asset_tag'],
            },
        ),
    ]
