# Generated by Django 5.2.1 on 2025-06-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic_iom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iomtemplate",
            name="fields_definition",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON schema defining the form fields for this IOM type.",
                verbose_name="Fields Definition",
            ),
        ),
    ]
