// itsm_frontend/src/modules/service-requests/types/ServiceRequestTypes.ts

export type ServiceRequestStatus = "new" | "in_progress" | "resolved" | "closed" | "cancelled";
export type ServiceRequestCategory = 'software' | 'hardware' | 'network' | 'information' | 'other';
export type ServiceRequestPriority = 'low' | 'medium' | 'high';

export interface ServiceRequest {
  id?: number; // Optional, generated by backend for new requests
  request_id?: string; // Generated by backend, read-only
  title: string;
  description: string;
  status: ServiceRequestStatus;
  category: ServiceRequestCategory;
  priority: ServiceRequestPriority;
requested_by_username: string; // Assuming these are now included directly
  assigned_to_username: string | null; // Assuming this can be null
  resolution_notes: string | null;
  created_at: string | null; // <-- Ensure this is 'string | null' or 'string | null | undefined'
  updated_at: string | null;
  resolved_at?: string | null; // ISO 8601 date string or null, read-only
}

// Type for data sent when creating a NEW service request

export interface NewServiceRequestData {
  title: string;
  description: string;
  requested_by_id: number;
  assigned_to_id: number | null;
  category: string;
  priority: string;
}