// itsm_frontend/src/modules/service-requests/types/ServiceRequestTypes.ts

export type ServiceRequestStatus = 'open' | 'in_progress' | 'resolved' | 'closed' | 'cancelled';
export type ServiceRequestCategory = 'software' | 'hardware' | 'network' | 'information' | 'other';
export type ServiceRequestPriority = 'low' | 'medium' | 'high';

export interface ServiceRequest {
  id?: number; // Optional, generated by backend for new requests
  request_id?: string; // Generated by backend, read-only
  title: string;
  description: string;
  status: ServiceRequestStatus;
  category: ServiceRequestCategory;
  priority: ServiceRequestPriority;
  requested_by: number; // User ID (number)
  requested_by_username?: string; // Read-only, for display
  assigned_to: number | null; // User ID (number) or null
  assigned_to_username?: string | null; // Read-only, for display
  resolution_notes: string | null;
  created_at?: string; // ISO 8601 date string, read-only
  updated_at?: string; // ISO 8601 date string, read-only
  resolved_at?: string | null; // ISO 8601 date string or null, read-only
}

// Type for data sent when creating a NEW service request
export interface NewServiceRequestData {
  title: string;
  description: string;
  status: ServiceRequestStatus;
  category: ServiceRequestCategory;
  priority: ServiceRequestPriority;
  // requested_by is typically set by the backend based on the authenticated user
  assigned_to?: number | null;
  resolution_notes?: string | null;
}