# Generated by Django 5.2.1 on 2025-06-18 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catalog Category',
                'verbose_name_plural': 'Catalog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(help_text='A brief summary of the service or item.', max_length=255)),
                ('full_description', models.TextField(blank=True, help_text='Detailed description, potentially with HTML or Markdown.', null=True)),
                ('estimated_fulfillment_time', models.CharField(blank=True, help_text="e.g., '2-3 business days', '1 hour'", max_length=100, null=True)),
                ('icon_url', models.URLField(blank=True, help_text='URL to an icon representing this item.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is currently available in the catalog.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service_catalog.catalogcategory')),
            ],
            options={
                'verbose_name': 'Catalog Item',
                'verbose_name_plural': 'Catalog Items',
                'ordering': ['category', 'name'],
            },
        ),
    ]
