# Generated by Django 5.2.3 on 2025-06-15 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Configuration Item', max_length=255, unique=True)),
                ('ci_type', models.CharField(choices=[('server', 'Server'), ('application', 'Application'), ('database', 'Database'), ('network_device', 'Network Device'), ('storage', 'Storage'), ('service', 'Business Service'), ('environment', 'Environment'), ('other', 'Other')], default='server', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deprecated', 'Deprecated'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('version', models.CharField(blank=True, help_text='Version of the CI (e.g., software version)', max_length=50)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_asset', models.ForeignKey(blank=True, help_text='Optional link to a specific IT Asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_items', to='assets.asset')),
                ('related_cis', models.ManyToManyField(blank=True, help_text='Other CIs this CI depends on or relates to', related_name='dependencies', to='configs.configurationitem')),
            ],
            options={
                'verbose_name': 'Configuration Item',
                'verbose_name_plural': 'Configuration Items',
                'ordering': ['name'],
            },
        ),
    ]
