# Generated by Django 5.2.1 on 2025-06-15 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(verbose_name='Item Description')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('reason', models.TextField(verbose_name='Reason for Purchase')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimated Cost')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('po_created', 'PO Created'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('decision_date', models.DateTimeField(blank=True, null=True, verbose_name='Decision Date')),
                ('approver_comments', models.TextField(blank=True, verbose_name='Approver Comments')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Purchase Request Memo',
                'verbose_name_plural': 'Purchase Request Memos',
                'ordering': ['-request_date'],
            },
        ),
    ]
