# Generated by Django 5.2.1 on 2025-06-15 18:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetcategory_location_vendor_alter_asset_category_and_more'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(help_text='Unique Purchase Order number', max_length=50, unique=True, verbose_name='PO Number')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Order Date')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Expected Delivery Date')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_address', models.TextField(blank=True, verbose_name='Shipping Address')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('internal_office_memo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order', to='procurement.purchaserequestmemo', verbose_name='Internal Office Memo')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='assets.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-order_date', '-po_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255, verbose_name='Item Description')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Price')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='procurement.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='CheckRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('payee_name', models.CharField(help_text='Typically the Vendor name, but can be overridden.', max_length=255, verbose_name='Payee Name')),
                ('payee_address', models.TextField(blank=True, verbose_name='Payee Address')),
                ('reason_for_payment', models.TextField(verbose_name='Reason for Payment / Description')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('status', models.CharField(choices=[('pending_submission', 'Pending Submission'), ('pending_approval', 'Pending Accounts Approval'), ('approved', 'Approved for Payment'), ('rejected', 'Rejected'), ('payment_processing', 'Payment Processing'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending_submission', max_length=30, verbose_name='Status')),
                ('accounts_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Accounts Approval Date')),
                ('accounts_comments', models.TextField(blank=True, verbose_name='Accounts Comments')),
                ('payment_method', models.CharField(blank=True, choices=[('check', 'Check'), ('ach', 'ACH Transfer'), ('wire', 'Wire Transfer'), ('cash', 'Cash'), ('credit_card', 'Credit Card'), ('other', 'Other')], max_length=20, null=True, verbose_name='Payment Method')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID / Check Number')),
                ('payment_notes', models.TextField(blank=True, verbose_name='Payment Notes')),
                ('approved_by_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_check_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved by Accounts')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_check_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_requests', to='procurement.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Check Request',
                'verbose_name_plural': 'Check Requests',
                'ordering': ['-request_date'],
            },
        ),
    ]
