# Generated by Django 5.2.1 on 2025-06-20 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_historicalasset"),
        ("procurement", "0002_purchaseorder_orderitem_checkrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Department Name"
                    ),
                ),
                (
                    "department_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Department Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Category Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GLAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="GL Account Code"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Account Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "GL Account",
                "verbose_name_plural": "GL Accounts",
                "ordering": ["account_code"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Project Name"
                    ),
                ),
                (
                    "project_code",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="Project Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="checkrequest",
            options={
                "ordering": ["-request_date"],
                "verbose_name": "Check Request (CR)",
                "verbose_name_plural": "Check Requests (CRs)",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "ordering": ["-order_date", "-po_number"],
                "verbose_name": "Purchase Order (PO)",
                "verbose_name_plural": "Purchase Orders (POs)",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaserequestmemo",
            options={
                "ordering": ["-request_date"],
                "verbose_name": "Purchase Request Memo (IOM)",
                "verbose_name_plural": "Purchase Request Memos (IOMs)",
            },
        ),
        migrations.AddField(
            model_name="checkrequest",
            name="attachments",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="procurement/cr_attachments/",
                verbose_name="Attachments",
            ),
        ),
        migrations.AddField(
            model_name="checkrequest",
            name="cr_id",
            field=models.CharField(
                blank=True,
                help_text="System-generated ID, e.g., CR-AA-0001. Consider auto-generation.",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="CR ID",
            ),
        ),
        migrations.AddField(
            model_name="checkrequest",
            name="currency",
            field=models.CharField(
                default="USD",
                help_text="e.g., USD, EUR, KES",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
        migrations.AddField(
            model_name="checkrequest",
            name="is_urgent",
            field=models.BooleanField(default=False, verbose_name="Is Urgent?"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_percentage_or_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Can be a percentage or a fixed amount. Clarify usage.",
                max_digits=10,
                null=True,
                verbose_name="Discount",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="line_item_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partially_received", "Partially Received"),
                    ("fully_received", "Fully Received"),
                    ("cancelled", "Cancelled"),
                    ("invoiced", "Invoiced"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Line Item Status",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_code",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Product Code/SKU"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="received_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Received Quantity"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tax_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="e.g., 16 for 16%",
                max_digits=5,
                null=True,
                verbose_name="Tax Rate (%)",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="attachments",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="procurement/po_attachments/",
                verbose_name="Attachments",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="billing_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Billing Address"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="currency",
            field=models.CharField(
                default="USD",
                help_text="e.g., USD, EUR, KES",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="payment_terms",
            field=models.CharField(
                blank=True,
                help_text="e.g., Net 30, Due on Receipt",
                max_length=100,
                verbose_name="Payment Terms",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="po_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("goods", "Goods"),
                    ("services", "Services"),
                    ("subscription", "Subscription"),
                    ("framework_agreement", "Framework Agreement"),
                ],
                max_length=30,
                null=True,
                verbose_name="PO Type",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="revision_number",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Revision Number"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="shipping_method",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Shipping Method"
            ),
        ),
        migrations.AddField(
            model_name="purchaserequestmemo",
            name="attachments",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="procurement/iom_attachments/",
                verbose_name="Attachments",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequestmemo",
            name="iom_id",
            field=models.CharField(
                blank=True,
                help_text="System-generated ID, e.g., IM-AA-0001. Consider auto-generation logic.",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="IOM ID",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequestmemo",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
                verbose_name="Priority",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequestmemo",
            name="required_delivery_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Required Delivery Date"
            ),
        ),
        migrations.AddField(
            model_name="purchaserequestmemo",
            name="suggested_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggested_purchase_requests",
                to="assets.vendor",
                verbose_name="Suggested Vendor",
            ),
        ),
        migrations.AlterField(
            model_name="checkrequest",
            name="payee_name",
            field=models.CharField(
                help_text="Typically the Vendor name from PO, but can be overridden.",
                max_length=255,
                verbose_name="Payee Name",
            ),
        ),
        migrations.AlterField(
            model_name="checkrequest",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="check_requests",
                to="procurement.purchaseorder",
                verbose_name="Related Purchase Order",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(
                help_text="Unique Purchase Order number, e.g., PO-AA-0001",
                max_length=50,
                unique=True,
                verbose_name="PO Number",
            ),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Contract ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "renewal_reminder_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Renewal Reminder Date"
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(blank=True, verbose_name="Terms & Conditions"),
                ),
                (
                    "attachments",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="procurement/contract_attachments/",
                        verbose_name="Attachments",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="assets.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="related_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="procurement.contract",
                verbose_name="Related Contract",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequestmemo",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_requests_memo",
                to="procurement.department",
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="checkrequest",
            name="expense_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="check_requests",
                to="procurement.expensecategory",
                verbose_name="Expense Category",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="gl_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="procurement.glaccount",
                verbose_name="GL Account",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequestmemo",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_requests_memo",
                to="procurement.project",
                verbose_name="Project",
            ),
        ),
        migrations.CreateModel(
            name="RecurringPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_name",
                    models.CharField(
                        max_length=150, verbose_name="Payment Name/Description"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        max_length=20,
                        verbose_name="Frequency",
                    ),
                ),
                ("next_due_date", models.DateField(verbose_name="Next Due Date")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active?"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "expense_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="procurement.expensecategory",
                    ),
                ),
                (
                    "gl_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="procurement.glaccount",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_payments",
                        to="assets.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring Payment",
                "verbose_name_plural": "Recurring Payments",
                "ordering": ["next_due_date"],
            },
        ),
        migrations.AddField(
            model_name="checkrequest",
            name="recurring_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="check_requests",
                to="procurement.recurringpayment",
                verbose_name="Recurring Payment",
            ),
        ),
    ]
