# Generated by Django 5.2.1 on 2025-06-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_purchaseorder_orderitem_checkrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckRequestSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_alpha_part_char1",
                    models.CharField(
                        default="A",
                        help_text="First character of the alphanumeric part (e.g., 'A' for XX-AA-0001)",
                        max_length=1,
                    ),
                ),
                (
                    "current_alpha_part_char2",
                    models.CharField(
                        default="A",
                        help_text="Second character of the alphanumeric part (e.g., 'A' for XX-AA-0001)",
                        max_length=1,
                    ),
                ),
                (
                    "current_numeric_part",
                    models.IntegerField(
                        default=0, help_text="Current numeric value (0-9999)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Check Request ID Sequence",
                "verbose_name_plural": "Check Request ID Sequences",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_alpha_part_char1",
                    models.CharField(
                        default="A",
                        help_text="First character of the alphanumeric part (e.g., 'A' for XX-AA-0001)",
                        max_length=1,
                    ),
                ),
                (
                    "current_alpha_part_char2",
                    models.CharField(
                        default="A",
                        help_text="Second character of the alphanumeric part (e.g., 'A' for XX-AA-0001)",
                        max_length=1,
                    ),
                ),
                (
                    "current_numeric_part",
                    models.IntegerField(
                        default=0, help_text="Current numeric value (0-9999)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order ID Sequence",
                "verbose_name_plural": "Purchase Order ID Sequences",
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequestMemoSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_alpha_part_char1",
                    models.CharField(
                        default="A",
                        help_text="First character of the alphanumeric part (e.g., 'A' for XX-AA-0001)",
                        max_length=1,
                    ),
                ),
                (
                    "current_alpha_part_char2",
                    models.CharField(
                        default="A",
                        help_text="Second character of the alphanumeric part (e.g., 'A' for XX-AA-0001)",
                        max_length=1,
                    ),
                ),
                (
                    "current_numeric_part",
                    models.IntegerField(
                        default=0, help_text="Current numeric value (0-9999)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Request Memo ID Sequence",
                "verbose_name_plural": "Purchase Request Memo ID Sequences",
            },
        ),
        migrations.AddField(
            model_name="checkrequest",
            name="cr_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unique Check Request ID (e.g., CR-AA-0001)",
                max_length=20,
                unique=True,
                verbose_name="CR ID",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequestmemo",
            name="iom_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unique Internal Office Memo ID (e.g., IM-AA-0001)",
                max_length=20,
                unique=True,
                verbose_name="IOM ID",
            ),
        ),
    ]
