# Generated by Django 5.2.1 on 2025-06-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_department_expensecategory_glaccount_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text="The prefix for the ID (e.g., 'IM', 'PO', 'CR')", max_length=3, unique=True, verbose_name='Prefix')),
                ('current_alpha_part_char1', models.CharField(default='A', help_text="First character of the alphanumeric part (e.g., 'A' for IM-AA-0001)", max_length=1)),
                ('current_alpha_part_char2', models.CharField(default='A', help_text="Second character of the alphanumeric part (e.g., 'A' for IM-AA-0001)", max_length=1)),
                ('current_numeric_part', models.PositiveIntegerField(default=0, help_text='Current numeric value (0-9999)')),
            ],
            options={
                'verbose_name': 'Procurement ID Sequence',
                'verbose_name_plural': 'Procurement ID Sequences',
                'ordering': ['prefix'],
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_percentage_or_amount',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='fixed', max_length=10, null=True, verbose_name='Discount Type'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value of the discount, either fixed amount or percentage (e.g., 10 for 10%)', max_digits=10, null=True, verbose_name='Discount Value'),
        ),
        migrations.AlterField(
            model_name='checkrequest',
            name='cr_id',
            field=models.CharField(blank=True, editable=False, help_text='System-generated ID, e.g., CR-YYMMDD-0001.', max_length=20, null=True, unique=True, verbose_name='CR ID'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, editable=False, help_text='System-generated PO number, e.g., PO-YYMMDD-0001', max_length=50, unique=True, verbose_name='PO Number'),
        ),
        migrations.AlterField(
            model_name='purchaserequestmemo',
            name='iom_id',
            field=models.CharField(blank=True, editable=False, help_text='System-generated ID, e.g., IM-YYMMDD-0001.', max_length=20, null=True, unique=True, verbose_name='IOM ID'),
        ),
    ]
