# Generated by Django 5.2.1 on 2025-06-23 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("procurement", "0004_procurementidsequence_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequestmemo",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("po_created", "PO Created"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="ApprovalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the rule, e.g., 'Dept Head Approval for > $1000'.",
                        max_length=255,
                        verbose_name="Rule Name",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="The order in which this rule/step should be evaluated or applied. Lower numbers come first.",
                        verbose_name="Order/Sequence",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum IOM estimated cost for this rule to apply. Leave blank if no minimum.",
                        max_digits=12,
                        null=True,
                        verbose_name="Minimum Amount",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum IOM estimated cost for this rule to apply. Leave blank if no maximum.",
                        max_digits=12,
                        null=True,
                        verbose_name="Maximum Amount",
                    ),
                ),
                (
                    "applies_to_all_departments",
                    models.BooleanField(
                        default=True, verbose_name="Applies to All Departments"
                    ),
                ),
                (
                    "applies_to_all_projects",
                    models.BooleanField(
                        default=True, verbose_name="Applies to All Projects"
                    ),
                ),
                (
                    "approval_level_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Department Head', 'Budget Holder', 'Director'. For display/logging.",
                        max_length=100,
                        null=True,
                        verbose_name="Approval Level Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to disable this rule.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "approver_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_rules_group",
                        to="auth.group",
                        verbose_name="Approver Group",
                    ),
                ),
                (
                    "approver_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_rules_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Specific Approver User",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If 'Applies to All Departments' is unchecked, select applicable departments.",
                        to="procurement.department",
                        verbose_name="Specific Departments",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If 'Applies to All Projects' is unchecked, select applicable projects.",
                        to="procurement.project",
                        verbose_name="Specific Projects",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Rule",
                "verbose_name_plural": "Approval Rules",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_name_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of the rule name at time of step creation.",
                        max_length=255,
                        verbose_name="Rule Name (Snapshot)",
                    ),
                ),
                ("step_order", models.PositiveIntegerField(verbose_name="Step Order")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped"),
                            ("delegated", "Delegated"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "decision_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Decision Date"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approval_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="procurement.approvalrule",
                        verbose_name="Originating Approval Rule",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actioned_approval_steps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actioned By User",
                    ),
                ),
                (
                    "assigned_approver_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_approval_steps_group",
                        to="auth.group",
                        verbose_name="Assigned Approver Group",
                    ),
                ),
                (
                    "assigned_approver_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_approval_steps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned Approver User",
                    ),
                ),
                (
                    "purchase_request_memo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_steps",
                        to="procurement.purchaserequestmemo",
                        verbose_name="Purchase Request Memo (IOM)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Step",
                "verbose_name_plural": "Approval Steps",
                "ordering": ["purchase_request_memo", "step_order", "created_at"],
            },
        ),
    ]
