# Generated by Django 5.2.1 on 2025-06-23 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0005_alter_purchaserequestmemo_status_approvalrule_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalDelegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Start Date")),
                ("end_date", models.DateTimeField(verbose_name="End Date")),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Reason for Delegation"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Delegation is only effective if active and within the date range.",
                        verbose_name="Is Active?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delegatee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Delegatee User",
                    ),
                ),
                (
                    "delegator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Delegator User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Delegation",
                "verbose_name_plural": "Approval Delegations",
                "ordering": ["-start_date"],
            },
        ),
    ]
