# Generated by Django 5.2.1 on 2025-06-29 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("generic_iom", "0001_initial"),
        ("procurement", "0007_alter_purchaserequestmemo_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalstep",
            options={
                "ordering": ["content_type", "object_id", "step_order", "created_at"],
                "verbose_name": "Approval Step",
                "verbose_name_plural": "Approval Steps",
            },
        ),
        migrations.RemoveField(
            model_name="approvalstep",
            name="purchase_request_memo",
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="applicable_iom_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="If Rule Type is 'Generic IOM', select categories this rule applies to.",
                to="generic_iom.iomcategory",
                verbose_name="Applicable IOM Categories (for Generic IOM)",
            ),
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="applicable_iom_templates",
            field=models.ManyToManyField(
                blank=True,
                help_text="If Rule Type is 'Generic IOM', select specific templates this rule applies to. Leave blank if applying via category.",
                to="generic_iom.iomtemplate",
                verbose_name="Applicable Specific IOM Templates (for Generic IOM)",
            ),
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("procurement_memo", "Procurement Memo (Purchase Request IOM)"),
                    ("generic_iom", "Generic IOM"),
                ],
                default="procurement_memo",
                help_text="Specify if this rule applies to Procurement Memos or Generic IOMs.",
                max_length=20,
                verbose_name="Rule Type",
            ),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Content Type of the item being approved (e.g., PurchaseRequestMemo or GenericIOM)",
            ),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Object ID of the item being approved",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrule",
            name="applies_to_all_departments",
            field=models.BooleanField(
                default=True,
                verbose_name="Applies to All Departments (for Procurement Memo)",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrule",
            name="applies_to_all_projects",
            field=models.BooleanField(
                default=True,
                verbose_name="Applies to All Projects (for Procurement Memo)",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrule",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                help_text="If 'Applies to All Departments' is unchecked, select applicable departments. Relevant if type is 'Procurement Memo'.",
                to="procurement.department",
                verbose_name="Specific Departments (for Procurement Memo)",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrule",
            name="max_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum IOM estimated cost for this rule to apply. Relevant if type is 'Procurement Memo'.",
                max_digits=12,
                null=True,
                verbose_name="Maximum Amount (for Procurement Memo)",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrule",
            name="min_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum IOM estimated cost for this rule to apply. Relevant if type is 'Procurement Memo'.",
                max_digits=12,
                null=True,
                verbose_name="Minimum Amount (for Procurement Memo)",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrule",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                help_text="If 'Applies to All Projects' is unchecked, select applicable projects. Relevant if type is 'Procurement Memo'.",
                to="procurement.project",
                verbose_name="Specific Projects (for Procurement Memo)",
            ),
        ),
        migrations.AlterField(
            model_name="checkrequest",
            name="cr_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="System-generated ID, e.g., CR-AA-0001.",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="CR ID",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="System-generated PO number, e.g., PO-AA-0001",
                max_length=50,
                unique=True,
                verbose_name="PO Number",
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequestmemo",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_purchase_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approver (Final Decider)",
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequestmemo",
            name="iom_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="System-generated ID, e.g., IM-AA-0001.",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="IOM ID",
            ),
        ),
    ]
