# Generated by Django 5.2.1 on 2025-06-29 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("procurement", "0008_alter_approvalstep_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalstep",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Content Type of the item being approved (e.g., PurchaseRequestMemo or GenericIOM)",
            ),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="object_id",
            field=models.PositiveIntegerField(
                verbose_name="Object ID of the item being approved"
            ),
        ),
    ]
