# Generated by Django 5.2.1 on 2025-06-30 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic_iom", "0003_load_sample_iom_templates"),
        ("procurement", "0009_alter_approvalstep_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="generic_iom_purchase_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the Generic IOM that represents the purchase request, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders_via_generic_iom",
                to="generic_iom.genericiom",
                verbose_name="Generic IOM Purchase Request",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="internal_office_memo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_order_legacy",
                to="procurement.purchaserequestmemo",
                verbose_name="Original Purchase Request Memo (Legacy)",
            ),
        ),
    ]
