# Generated by Django 5.2.1 on 2025-06-18 04:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_historicalasset'),
        ('configs', '0001_initial'),
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='calculated_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority calculated based on impact and urgency', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='sla_resolve_target_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA Resolution Target'),
        ),
        migrations.AddField(
            model_name='incident',
            name='sla_response_target_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA Response Target'),
        ),
        migrations.CreateModel(
            name='HistoricalIncident',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief summary of the incident', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Effect on business operations', max_length=20)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Speed at which incident needs to be resolved', max_length=20)),
                ('calculated_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority calculated based on impact and urgency', max_length=20)),
                ('sla_response_target_at', models.DateTimeField(blank=True, null=True, verbose_name='SLA Response Target')),
                ('sla_resolve_target_at', models.DateTimeField(blank=True, null=True, verbose_name='SLA Resolution Target')),
                ('resolution_notes', models.TextField(blank=True, help_text='Details on how the incident was resolved', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, help_text='IT staff assigned to resolve the incident', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_asset', models.ForeignKey(blank=True, db_constraint=False, help_text='Primary asset affected by this incident', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.asset')),
                ('related_ci', models.ForeignKey(blank=True, db_constraint=False, help_text='Primary Configuration Item affected by this incident', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configs.configurationitem')),
                ('reported_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who reported the incident', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Incident',
                'verbose_name_plural': 'historical Incidents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
